version: 2
jobs:
    build:
        environment:
            NODE_ENV: development
        docker:
            - {image: 'circleci/node:10.0.0'}
            - {image: redis}
        working_directory: ~/limitrr
        steps:
            - checkout
            - {run: {name: update-npm, command: 'sudo npm install -g npm@latest'}}
            - {restore_cache: {keys: ['v1-dependencies-{{ checksum "package.json" }}', v1-dependencies-]}}
            - {run: 'npm install'}
            - {run: 'npm install mocha-junit-reporter nyc eslint'}
            - {save_cache: {paths: [node_modules], key: 'v1-dependencies-{{ checksum "package.json" }}'}}
            - {run: 'mkdir reports'}
            - {run: {name: 'npm test', command: './node_modules/.bin/nyc ./node_modules/.bin/mocha --recursive --timeout=10000 --exit --reporter mocha-junit-reporter --reporter-options mochaFile=reports/mocha/test-results.xml', when: always}}
            - {store_test_results: {path: reports}}
            - {store_artifacts: {path: ./reports/mocha/test-results.xml}}
